### ISSUE TITLE
Errors When Library Attempt to Access Upgrades and Unselected Subscriptions from Prior Years

### ISSUE THREAD

**Issue by CClennon** [CARLI/select#57] opened 2018-05-17 21:13 UTC
This was first pointed out to us by Lake Forest College this morning. When attempting to masquerade as them and access Fiscal Year 2018 Upgrades and Unselected products they (and we) get the following error message:

Unknown error
Cannot read property ‘filter’ or undefined

I just tried again and was able to access the FY18 pricing.  But for all other earlier periods I receive the error messages. There were also times when a report would populate but it contained the FY18 products and pricing (when the request was not for FY18 data).

As it includes pricing data I will email a screen capture so you can see the results of attempting to retrieve data for any period other than FY18.

**Comment by CClennon** [comment] 2018-06-08 19:34
Hi Marty,

That sounds like a good plan.   Please proceed.

Have a great weekend,

Cindy

Cindy Clennon
Director of Electronic Resources
Consortium of Academic and Research Libraries in Illinois (CARLI)
100 Trade Centre Drive, Suite 303
Champaign, IL 61820-7233
Ph: 217-333-4895
Fax: 217-244-7596
clennon@uillinois.edu
www.carli.illinois.edu<http://www.carli.illinois.edu/>

"Under the Illinois Freedom of Information Act (FOIA), any written communication to or from university employees regarding University business is a public record and may be subject to public disclosure."

**Comment by mekane** [comment] 2018-06-21 20:00
Turns out this is a duplicate of #52 which has already been fixed but not yet pushed to production.

**Closed by mekane** 2018-06-21 20:00 UTC
Labels: Pixo-work-2018, bug
